---
deployment:
  tasks:
    - export DEPLOYPATH="$HOME/ebravoholding.com/pages/vida-alem-da-tela/"
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp assets/* $DEPLOYPATH/assets/
